--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ems_alarm_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_alarm_config (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_enabled boolean,
    limit_value numeric(10,4),
    meter_point_id bigint NOT NULL,
    remark character varying(500),
    limit_type_id bigint NOT NULL
);


ALTER TABLE public.ems_alarm_config OWNER TO postgres;

--
-- Name: ems_alarm_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_alarm_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_alarm_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_alarm_limit_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_alarm_limit_type (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    alarm_type character varying(20),
    color_number character varying(20),
    comparator_operator character varying(10),
    limit_code character varying(50) NOT NULL,
    limit_name character varying(100) NOT NULL
);


ALTER TABLE public.ems_alarm_limit_type OWNER TO postgres;

--
-- Name: ems_alarm_limit_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_alarm_limit_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_alarm_limit_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_alarm_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_alarm_record (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    handle_remark character varying(500),
    handle_time timestamp(6) without time zone,
    status integer,
    trigger_time timestamp(6) without time zone NOT NULL,
    trigger_value numeric(10,4),
    config_id bigint NOT NULL
);


ALTER TABLE public.ems_alarm_record OWNER TO postgres;

--
-- Name: ems_alarm_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_alarm_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_alarm_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_benchmark; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_benchmark (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(50) NOT NULL,
    grade character varying(20),
    name character varying(100) NOT NULL,
    national_num character varying(50),
    remark character varying(500),
    status smallint,
    type character varying(20),
    unit character varying(20),
    value numeric(12,4),
    energy_type_id bigint,
    CONSTRAINT ems_benchmark_status_check CHECK (((status >= 0) AND (status <= 1))),
    CONSTRAINT ems_benchmark_type_check CHECK (((type)::text = ANY ((ARRAY['NATIONAL'::character varying, 'INDUSTRY'::character varying, 'ENTERPRISE'::character varying, 'REGIONAL'::character varying])::text[])))
);


ALTER TABLE public.ems_benchmark OWNER TO postgres;

--
-- Name: ems_benchmark_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_benchmark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_benchmark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_cost_policy_binding; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_cost_policy_binding (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    effective_end_date date,
    effective_start_date date NOT NULL,
    remark character varying(500),
    status smallint,
    energy_unit_id bigint NOT NULL,
    price_policy_id bigint NOT NULL,
    CONSTRAINT ems_cost_policy_binding_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_cost_policy_binding OWNER TO postgres;

--
-- Name: ems_cost_policy_binding_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_cost_policy_binding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_cost_policy_binding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_data_source; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_data_source (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    connection text,
    last_seen_time timestamp(6) without time zone,
    name character varying(150) NOT NULL,
    poll_interval_secs integer,
    protocol character varying(30) NOT NULL,
    remark character varying(500),
    status smallint NOT NULL,
    gateway_id bigint NOT NULL,
    CONSTRAINT ems_data_source_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_data_source OWNER TO postgres;

--
-- Name: ems_data_source_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_data_source ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_data_source_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_energy_cost_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_energy_cost_record (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    consumption numeric(14,4),
    cost numeric(14,2),
    flat_consumption numeric(14,4),
    peak_consumption numeric(14,4),
    period_type character varying(10),
    power_factor numeric(5,2),
    record_date date NOT NULL,
    remark character varying(500),
    sharp_consumption numeric(14,4),
    valley_consumption numeric(14,4),
    energy_type_id bigint,
    energy_unit_id bigint,
    CONSTRAINT ems_energy_cost_record_period_type_check CHECK (((period_type)::text = ANY ((ARRAY['DAY'::character varying, 'MONTH'::character varying, 'YEAR'::character varying])::text[])))
);


ALTER TABLE public.ems_energy_cost_record OWNER TO postgres;

--
-- Name: ems_energy_cost_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_energy_cost_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_energy_cost_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_energy_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_energy_data (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    data_time timestamp(6) without time zone NOT NULL,
    time_type character varying(10) NOT NULL,
    value numeric(18,4),
    energy_type_id bigint NOT NULL,
    meter_point_id bigint NOT NULL
);


ALTER TABLE public.ems_energy_data OWNER TO postgres;

--
-- Name: ems_energy_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_energy_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_energy_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_energy_saving_project; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_energy_saving_project (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    plan text,
    implementation_plan text,
    current_work character varying(500),
    liable_person character varying(50),
    saving_amount numeric(12,2),
    completion_time date,
    status character varying(20) DEFAULT 'PLANNING'::character varying,
    remark character varying(500),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.ems_energy_saving_project OWNER TO postgres;

--
-- Name: ems_energy_saving_project_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ems_energy_saving_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ems_energy_saving_project_id_seq OWNER TO postgres;

--
-- Name: ems_energy_saving_project_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ems_energy_saving_project_id_seq OWNED BY public.ems_energy_saving_project.id;


--
-- Name: ems_energy_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_energy_type (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(20),
    code character varying(50) NOT NULL,
    coefficient numeric(10,4),
    color character varying(20),
    default_price numeric(10,4),
    emission_factor numeric(10,4),
    icon character varying(50),
    name character varying(100) NOT NULL,
    remark character varying(500),
    sort_order integer,
    status smallint NOT NULL,
    storable boolean NOT NULL,
    unit character varying(20) NOT NULL,
    CONSTRAINT ems_energy_type_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_energy_type OWNER TO postgres;

--
-- Name: ems_energy_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_energy_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_energy_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_energy_unit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_energy_unit (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(50) NOT NULL,
    level integer NOT NULL,
    name character varying(100) NOT NULL,
    remark character varying(500),
    sort_order integer,
    status smallint NOT NULL,
    parent_id bigint,
    rated_current numeric(10,2),
    rated_power numeric(12,2),
    unit_type character varying(20),
    voltage_level character varying(20),
    CONSTRAINT ems_energy_unit_status_check CHECK (((status >= 0) AND (status <= 1))),
    CONSTRAINT ems_energy_unit_unit_type_check CHECK (((unit_type)::text = ANY ((ARRAY['GENERAL'::character varying, 'BRANCH'::character varying, 'PROCESS'::character varying, 'EQUIPMENT'::character varying])::text[])))
);


ALTER TABLE public.ems_energy_unit OWNER TO postgres;

--
-- Name: ems_energy_unit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_energy_unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_energy_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_energy_unit_point; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_energy_unit_point (
    meter_point_id bigint NOT NULL,
    energy_unit_id bigint NOT NULL
);


ALTER TABLE public.ems_energy_unit_point OWNER TO postgres;

--
-- Name: ems_equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_equipment (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(50) NOT NULL,
    location character varying(300),
    manufacturer character varying(255),
    model_number character varying(150),
    name character varying(150) NOT NULL,
    rated_power numeric(12,2),
    remark character varying(500),
    sort_order integer,
    status smallint NOT NULL,
    type character varying(50),
    energy_unit_id bigint,
    CONSTRAINT ems_equipment_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_equipment OWNER TO postgres;

--
-- Name: ems_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_gateway; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_gateway (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(50) NOT NULL,
    install_location character varying(300),
    ip_address character varying(50),
    last_heartbeat timestamp(6) without time zone,
    manufacturer character varying(255),
    model character varying(150),
    name character varying(150) NOT NULL,
    remark character varying(500),
    run_status character varying(20),
    status smallint NOT NULL,
    energy_unit_id bigint,
    cpu_usage double precision,
    mem_usage double precision,
    CONSTRAINT ems_gateway_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_gateway OWNER TO postgres;

--
-- Name: ems_gateway_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_gateway ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_gateway_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_knowledge_article; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_knowledge_article (
    id bigint NOT NULL,
    author character varying(50),
    category character varying(50),
    content text,
    energy_type_id bigint,
    sort_order integer,
    status smallint NOT NULL,
    summary character varying(500),
    title character varying(200) NOT NULL,
    view_count integer DEFAULT 0 NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT ems_knowledge_article_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_knowledge_article OWNER TO postgres;

--
-- Name: ems_knowledge_article_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_knowledge_article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_knowledge_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_meter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_meter (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    check_cycle integer,
    code character varying(50) NOT NULL,
    location character varying(300),
    manufacturer character varying(255),
    max_power character varying(255),
    measure_range character varying(150),
    model_number character varying(150),
    name character varying(150) NOT NULL,
    person_charge character varying(200),
    putrun_time date,
    remark character varying(500),
    reminder_cycle integer,
    start_time date,
    status smallint NOT NULL,
    type character varying(20) NOT NULL,
    wire_diameter character varying(255),
    energy_type_id bigint,
    comm_params text,
    data_source_id bigint,
    equipment_id bigint,
    gateway_id bigint,
    energy_unit_id bigint,
    CONSTRAINT ems_meter_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_meter OWNER TO postgres;

--
-- Name: ems_meter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_meter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_meter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_meter_point; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_meter_point (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category character varying(20),
    code character varying(50) NOT NULL,
    initial_value numeric(15,4),
    max_value numeric(15,4),
    min_value numeric(15,4),
    name character varying(100) NOT NULL,
    point_type character varying(20) NOT NULL,
    remark character varying(500),
    sort_order integer,
    status smallint NOT NULL,
    step_max numeric(15,4),
    step_min numeric(15,4),
    unit character varying(20),
    energy_type_id bigint,
    meter_id bigint,
    acquisition_params text,
    measure_type character varying(20),
    CONSTRAINT ems_meter_point_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_meter_point OWNER TO postgres;

--
-- Name: ems_meter_point_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_meter_point ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_meter_point_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_peak_valley_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_peak_valley_data (
    id bigint NOT NULL,
    cost numeric(18,4),
    created_at timestamp(6) without time zone,
    data_time date NOT NULL,
    electricity numeric(18,4),
    energy_unit_id bigint,
    meter_point_id bigint NOT NULL,
    period_type character varying(20) NOT NULL,
    price numeric(10,4),
    time_type character varying(10) NOT NULL,
    CONSTRAINT ems_peak_valley_data_period_type_check CHECK (((period_type)::text = ANY ((ARRAY['SHARP'::character varying, 'PEAK'::character varying, 'FLAT'::character varying, 'VALLEY'::character varying, 'DEEP_VALLEY'::character varying])::text[])))
);


ALTER TABLE public.ems_peak_valley_data OWNER TO postgres;

--
-- Name: ems_peak_valley_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_peak_valley_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_peak_valley_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_policy; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_policy (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    type character varying(20) DEFAULT 'NATIONAL'::character varying,
    department character varying(100),
    issuing_date date,
    file_url character varying(500),
    summary text,
    status integer DEFAULT 0,
    remark character varying(500),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.ems_policy OWNER TO postgres;

--
-- Name: ems_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ems_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ems_policy_id_seq OWNER TO postgres;

--
-- Name: ems_policy_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ems_policy_id_seq OWNED BY public.ems_policy.id;


--
-- Name: ems_price_policy; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_price_policy (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(50) NOT NULL,
    is_multi_rate boolean,
    name character varying(100) NOT NULL,
    remark character varying(500),
    sort_order integer,
    status smallint,
    energy_type_id bigint DEFAULT 1,
    effective_end_date date,
    effective_start_date date,
    CONSTRAINT ems_price_policy_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_price_policy OWNER TO postgres;

--
-- Name: ems_price_policy_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_price_policy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_price_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_price_policy_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_price_policy_item (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    period_type character varying(20) NOT NULL,
    price numeric(10,4) NOT NULL,
    remark character varying(200),
    sort_order integer,
    policy_id bigint NOT NULL,
    end_time character varying(10),
    start_time character varying(10),
    CONSTRAINT ems_price_policy_item_period_type_check CHECK (((period_type)::text = ANY ((ARRAY['SHARP'::character varying, 'PEAK'::character varying, 'FLAT'::character varying, 'VALLEY'::character varying, 'DEEP'::character varying])::text[])))
);


ALTER TABLE public.ems_price_policy_item OWNER TO postgres;

--
-- Name: ems_price_policy_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_price_policy_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_price_policy_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_product (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    remark character varying(500),
    sort_order integer,
    status smallint NOT NULL,
    type character varying(50),
    unit character varying(20),
    CONSTRAINT ems_product_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_product OWNER TO postgres;

--
-- Name: ems_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_production_record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_production_record (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    energy_unit_id bigint NOT NULL,
    granularity character varying(20) NOT NULL,
    product_name character varying(100) NOT NULL,
    quantity numeric(18,4) NOT NULL,
    record_date timestamp without time zone NOT NULL,
    remark character varying(500),
    unit character varying(20),
    data_type character varying(10) NOT NULL,
    product_type character varying(50),
    CONSTRAINT ems_production_record_granularity_check CHECK (((granularity)::text = ANY ((ARRAY['HOUR'::character varying, 'DAY'::character varying, 'MONTH'::character varying, 'YEAR'::character varying])::text[])))
);


ALTER TABLE public.ems_production_record OWNER TO postgres;

--
-- Name: ems_production_record_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_production_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_production_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ems_time_period_price; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ems_time_period_price (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    end_time time(6) without time zone NOT NULL,
    period_name character varying(50) NOT NULL,
    period_type character varying(20) NOT NULL,
    price numeric(10,4) NOT NULL,
    price_policy_id bigint,
    remark character varying(500),
    sort_order integer,
    start_time time(6) without time zone NOT NULL,
    status smallint,
    CONSTRAINT ems_time_period_price_period_type_check CHECK (((period_type)::text = ANY ((ARRAY['SHARP'::character varying, 'PEAK'::character varying, 'FLAT'::character varying, 'VALLEY'::character varying, 'DEEP_VALLEY'::character varying])::text[]))),
    CONSTRAINT ems_time_period_price_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.ems_time_period_price OWNER TO postgres;

--
-- Name: ems_time_period_price_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ems_time_period_price ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ems_time_period_price_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_config (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    config_key character varying(100) NOT NULL,
    config_name character varying(100),
    config_type character varying(1),
    config_value character varying(500),
    remark character varying(500)
);


ALTER TABLE public.sys_config OWNER TO postgres;

--
-- Name: sys_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_dept; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_dept (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    ancestors character varying(255),
    code character varying(32),
    email character varying(64),
    leader character varying(32),
    name character varying(64) NOT NULL,
    phone character varying(11),
    sort_order integer,
    status smallint NOT NULL,
    parent_id bigint,
    manager_id bigint,
    description character varying(512),
    CONSTRAINT sys_dept_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.sys_dept OWNER TO postgres;

--
-- Name: sys_dept_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_dept ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_dept_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_dict_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_dict_data (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_default character varying(1),
    label character varying(100) NOT NULL,
    remark character varying(500),
    sort_order bigint,
    status character varying(1),
    tag_color character varying(100),
    tag_type character varying(100),
    type_code character varying(100) NOT NULL,
    value character varying(100) NOT NULL
);


ALTER TABLE public.sys_dict_data OWNER TO postgres;

--
-- Name: sys_dict_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_dict_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_dict_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_dict_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_dict_type (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(100) NOT NULL,
    remark character varying(500),
    status character varying(1),
    type character varying(100) NOT NULL
);


ALTER TABLE public.sys_dict_type OWNER TO postgres;

--
-- Name: sys_dict_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_dict_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_dict_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_log (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    business_type integer,
    cost_time bigint,
    dept_name character varying(50),
    error_msg text,
    ip character varying(128),
    location character varying(255),
    log_type character varying(10) NOT NULL,
    method character varying(100),
    param text,
    request_method character varying(10),
    result text,
    status integer,
    title character varying(50),
    url character varying(255),
    username character varying(50)
);


ALTER TABLE public.sys_log OWNER TO postgres;

--
-- Name: sys_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_login_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_login_log (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    browser character varying(50),
    ipaddr character varying(128),
    login_location character varying(255),
    login_time timestamp(6) without time zone,
    msg character varying(255),
    os character varying(50),
    status character varying(1),
    user_name character varying(50)
);


ALTER TABLE public.sys_login_log OWNER TO postgres;

--
-- Name: sys_login_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_login_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_login_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_menu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_menu (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    component character varying(255),
    icon character varying(100),
    menu_type character varying(1) NOT NULL,
    name character varying(50) NOT NULL,
    path character varying(200),
    permission_code character varying(100),
    sort_order integer,
    status smallint NOT NULL,
    visible character varying(1),
    parent_id bigint,
    CONSTRAINT sys_menu_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.sys_menu OWNER TO postgres;

--
-- Name: sys_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_module; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_module (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(64) NOT NULL,
    name character varying(128) NOT NULL,
    sort_order integer
);


ALTER TABLE public.sys_module OWNER TO postgres;

--
-- Name: sys_module_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_module ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_module_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_notice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_notice (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    notice_content oid,
    notice_title character varying(50) NOT NULL,
    notice_type character varying(1) NOT NULL,
    remark character varying(255),
    status smallint NOT NULL,
    CONSTRAINT sys_notice_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.sys_notice OWNER TO postgres;

--
-- Name: sys_notice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_notice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_operation_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_operation_log (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    business_type integer,
    cost_time bigint,
    dept_name character varying(50),
    error_msg text,
    json_result text,
    method character varying(100),
    oper_ip character varying(128),
    oper_location character varying(255),
    oper_name character varying(50),
    oper_param text,
    oper_time timestamp(6) without time zone,
    oper_url character varying(255),
    operator_type integer,
    request_method character varying(10),
    status integer,
    title character varying(50),
    operation_ip character varying(128),
    operation_location character varying(255),
    operation_name character varying(50),
    operation_param text,
    operation_time timestamp(6) without time zone,
    operation_url character varying(255)
);


ALTER TABLE public.sys_operation_log OWNER TO postgres;

--
-- Name: sys_operation_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_operation_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_operation_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_permission (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(64) NOT NULL,
    description character varying(500),
    name character varying(128) NOT NULL,
    super_permission boolean,
    module_id bigint
);


ALTER TABLE public.sys_permission OWNER TO postgres;

--
-- Name: sys_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_post (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(64) NOT NULL,
    name character varying(64) NOT NULL,
    remark character varying(500),
    sort_order integer,
    status smallint NOT NULL,
    CONSTRAINT sys_post_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.sys_post OWNER TO postgres;

--
-- Name: sys_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_role (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(64) NOT NULL,
    member_count integer DEFAULT 0 NOT NULL,
    name character varying(128) NOT NULL,
    permission_count integer DEFAULT 0 NOT NULL,
    remark character varying(500),
    data_scope character varying(20),
    status smallint NOT NULL,
    CONSTRAINT sys_role_data_scope_check CHECK (((data_scope)::text = ANY ((ARRAY['ALL'::character varying, 'DEPT'::character varying, 'DEPT_AND_CHILD'::character varying, 'SELF'::character varying, 'CUSTOM'::character varying])::text[]))),
    CONSTRAINT sys_role_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.sys_role OWNER TO postgres;

--
-- Name: sys_role_dept; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_role_dept (
    role_id bigint NOT NULL,
    dept_id bigint
);


ALTER TABLE public.sys_role_dept OWNER TO postgres;

--
-- Name: sys_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_role_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_role_permission (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.sys_role_permission OWNER TO postgres;

--
-- Name: sys_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_user (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(128),
    nickname character varying(64),
    password character varying(128) NOT NULL,
    phone character varying(20),
    status integer NOT NULL,
    username character varying(64) NOT NULL,
    account_expire_at timestamp(6) without time zone,
    credentials_expire_at timestamp(6) without time zone,
    fail_login_count integer DEFAULT 0 NOT NULL,
    last_login_at timestamp(6) without time zone,
    avatar character varying(256),
    dept_id bigint,
    employee_no character varying(32),
    gender smallint,
    remark character varying(512),
    real_name character varying(64),
    super_admin boolean,
    CONSTRAINT sys_user_gender_check CHECK (((gender >= 0) AND (gender <= 2)))
);


ALTER TABLE public.sys_user OWNER TO postgres;

--
-- Name: sys_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_user_notice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_user_notice (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    notice_id bigint NOT NULL,
    read_time timestamp(6) without time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.sys_user_notice OWNER TO postgres;

--
-- Name: sys_user_notice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sys_user_notice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_user_notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_user_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_user_permission (
    user_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.sys_user_permission OWNER TO postgres;

--
-- Name: sys_user_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_user_post (
    user_id bigint NOT NULL,
    post_id bigint NOT NULL
);


ALTER TABLE public.sys_user_post OWNER TO postgres;

--
-- Name: sys_user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sys_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.sys_user_role OWNER TO postgres;

--
-- Name: ems_energy_saving_project id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_saving_project ALTER COLUMN id SET DEFAULT nextval('public.ems_energy_saving_project_id_seq'::regclass);


--
-- Name: ems_policy id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_policy ALTER COLUMN id SET DEFAULT nextval('public.ems_policy_id_seq'::regclass);


--
-- Name: ems_alarm_config ems_alarm_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_alarm_config
    ADD CONSTRAINT ems_alarm_config_pkey PRIMARY KEY (id);


--
-- Name: ems_alarm_limit_type ems_alarm_limit_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_alarm_limit_type
    ADD CONSTRAINT ems_alarm_limit_type_pkey PRIMARY KEY (id);


--
-- Name: ems_alarm_record ems_alarm_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_alarm_record
    ADD CONSTRAINT ems_alarm_record_pkey PRIMARY KEY (id);


--
-- Name: ems_benchmark ems_benchmark_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_benchmark
    ADD CONSTRAINT ems_benchmark_pkey PRIMARY KEY (id);


--
-- Name: ems_cost_policy_binding ems_cost_policy_binding_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_cost_policy_binding
    ADD CONSTRAINT ems_cost_policy_binding_pkey PRIMARY KEY (id);


--
-- Name: ems_data_source ems_data_source_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_data_source
    ADD CONSTRAINT ems_data_source_pkey PRIMARY KEY (id);


--
-- Name: ems_energy_cost_record ems_energy_cost_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_cost_record
    ADD CONSTRAINT ems_energy_cost_record_pkey PRIMARY KEY (id);


--
-- Name: ems_energy_data ems_energy_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_data
    ADD CONSTRAINT ems_energy_data_pkey PRIMARY KEY (id);


--
-- Name: ems_energy_saving_project ems_energy_saving_project_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_saving_project
    ADD CONSTRAINT ems_energy_saving_project_pkey PRIMARY KEY (id);


--
-- Name: ems_energy_type ems_energy_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_type
    ADD CONSTRAINT ems_energy_type_pkey PRIMARY KEY (id);


--
-- Name: ems_energy_unit ems_energy_unit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_unit
    ADD CONSTRAINT ems_energy_unit_pkey PRIMARY KEY (id);


--
-- Name: ems_energy_unit_point ems_energy_unit_point_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_unit_point
    ADD CONSTRAINT ems_energy_unit_point_pkey PRIMARY KEY (meter_point_id, energy_unit_id);


--
-- Name: ems_equipment ems_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_equipment
    ADD CONSTRAINT ems_equipment_pkey PRIMARY KEY (id);


--
-- Name: ems_gateway ems_gateway_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_gateway
    ADD CONSTRAINT ems_gateway_pkey PRIMARY KEY (id);


--
-- Name: ems_knowledge_article ems_knowledge_article_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_knowledge_article
    ADD CONSTRAINT ems_knowledge_article_pkey PRIMARY KEY (id);


--
-- Name: ems_meter ems_meter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter
    ADD CONSTRAINT ems_meter_pkey PRIMARY KEY (id);


--
-- Name: ems_meter_point ems_meter_point_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter_point
    ADD CONSTRAINT ems_meter_point_pkey PRIMARY KEY (id);


--
-- Name: ems_peak_valley_data ems_peak_valley_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_peak_valley_data
    ADD CONSTRAINT ems_peak_valley_data_pkey PRIMARY KEY (id);


--
-- Name: ems_policy ems_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_policy
    ADD CONSTRAINT ems_policy_pkey PRIMARY KEY (id);


--
-- Name: ems_price_policy_item ems_price_policy_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_price_policy_item
    ADD CONSTRAINT ems_price_policy_item_pkey PRIMARY KEY (id);


--
-- Name: ems_price_policy ems_price_policy_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_price_policy
    ADD CONSTRAINT ems_price_policy_pkey PRIMARY KEY (id);


--
-- Name: ems_product ems_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_product
    ADD CONSTRAINT ems_product_pkey PRIMARY KEY (id);


--
-- Name: ems_production_record ems_production_record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_production_record
    ADD CONSTRAINT ems_production_record_pkey PRIMARY KEY (id);


--
-- Name: ems_time_period_price ems_time_period_price_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_time_period_price
    ADD CONSTRAINT ems_time_period_price_pkey PRIMARY KEY (id);


--
-- Name: sys_dict_type idx_dict_type; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_dict_type
    ADD CONSTRAINT idx_dict_type UNIQUE (type);


--
-- Name: sys_config sys_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_config
    ADD CONSTRAINT sys_config_pkey PRIMARY KEY (id);


--
-- Name: sys_dept sys_dept_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_dept
    ADD CONSTRAINT sys_dept_pkey PRIMARY KEY (id);


--
-- Name: sys_dict_data sys_dict_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_dict_data
    ADD CONSTRAINT sys_dict_data_pkey PRIMARY KEY (id);


--
-- Name: sys_dict_type sys_dict_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_dict_type
    ADD CONSTRAINT sys_dict_type_pkey PRIMARY KEY (id);


--
-- Name: sys_log sys_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_log
    ADD CONSTRAINT sys_log_pkey PRIMARY KEY (id);


--
-- Name: sys_login_log sys_login_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_login_log
    ADD CONSTRAINT sys_login_log_pkey PRIMARY KEY (id);


--
-- Name: sys_menu sys_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_menu
    ADD CONSTRAINT sys_menu_pkey PRIMARY KEY (id);


--
-- Name: sys_module sys_module_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_module
    ADD CONSTRAINT sys_module_pkey PRIMARY KEY (id);


--
-- Name: sys_notice sys_notice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_notice
    ADD CONSTRAINT sys_notice_pkey PRIMARY KEY (id);


--
-- Name: sys_operation_log sys_operation_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_operation_log
    ADD CONSTRAINT sys_operation_log_pkey PRIMARY KEY (id);


--
-- Name: sys_permission sys_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_permission
    ADD CONSTRAINT sys_permission_pkey PRIMARY KEY (id);


--
-- Name: sys_post sys_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_post
    ADD CONSTRAINT sys_post_pkey PRIMARY KEY (id);


--
-- Name: sys_role_permission sys_role_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_role_permission
    ADD CONSTRAINT sys_role_permission_pkey PRIMARY KEY (role_id, permission_id);


--
-- Name: sys_role sys_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_role
    ADD CONSTRAINT sys_role_pkey PRIMARY KEY (id);


--
-- Name: sys_user_notice sys_user_notice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_notice
    ADD CONSTRAINT sys_user_notice_pkey PRIMARY KEY (id);


--
-- Name: sys_user_permission sys_user_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_permission
    ADD CONSTRAINT sys_user_permission_pkey PRIMARY KEY (user_id, permission_id);


--
-- Name: sys_user sys_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT sys_user_pkey PRIMARY KEY (id);


--
-- Name: sys_user_post sys_user_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_post
    ADD CONSTRAINT sys_user_post_pkey PRIMARY KEY (user_id, post_id);


--
-- Name: sys_user_role sys_user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_role
    ADD CONSTRAINT sys_user_role_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: ems_energy_unit uk1dd9o4p4mktlib0tq3gpnl2gu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_unit
    ADD CONSTRAINT uk1dd9o4p4mktlib0tq3gpnl2gu UNIQUE (code);


--
-- Name: sys_permission uk2vm98en2ouht0v15fvef2whp4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_permission
    ADD CONSTRAINT uk2vm98en2ouht0v15fvef2whp4 UNIQUE (code);


--
-- Name: sys_user uk51bvuyvihefoh4kp5syh2jpi4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT uk51bvuyvihefoh4kp5syh2jpi4 UNIQUE (username);


--
-- Name: ems_gateway uk540tj2jwrnu736khhw3kkou6f; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_gateway
    ADD CONSTRAINT uk540tj2jwrnu736khhw3kkou6f UNIQUE (code);


--
-- Name: ems_benchmark uk541184xedrs6lp0yd95kiplis; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_benchmark
    ADD CONSTRAINT uk541184xedrs6lp0yd95kiplis UNIQUE (code);


--
-- Name: ems_meter uk5xsxp2n696rrf80766t933ly8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter
    ADD CONSTRAINT uk5xsxp2n696rrf80766t933ly8 UNIQUE (code);


--
-- Name: sys_dict_data uk_dict_data_value_type; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_dict_data
    ADD CONSTRAINT uk_dict_data_value_type UNIQUE (value, type_code);


--
-- Name: ems_alarm_limit_type ukco6bbk2823t0js0qnrd41naxu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_alarm_limit_type
    ADD CONSTRAINT ukco6bbk2823t0js0qnrd41naxu UNIQUE (limit_code);


--
-- Name: sys_user_notice uke8tesnqlq4mwewoyko7609fxb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_notice
    ADD CONSTRAINT uke8tesnqlq4mwewoyko7609fxb UNIQUE (user_id, notice_id);


--
-- Name: sys_config ukellx5pgxddrdrfyvtfbgxccvl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_config
    ADD CONSTRAINT ukellx5pgxddrdrfyvtfbgxccvl UNIQUE (config_key);


--
-- Name: ems_equipment ukhm2u8wcbuaq9ayj62omxvuq67; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_equipment
    ADD CONSTRAINT ukhm2u8wcbuaq9ayj62omxvuq67 UNIQUE (code);


--
-- Name: ems_product ukj7ymku309maor470onudrjq3n; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_product
    ADD CONSTRAINT ukj7ymku309maor470onudrjq3n UNIQUE (code);


--
-- Name: ems_meter_point ukjb553gu8ityk06dbghpfbmroy; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter_point
    ADD CONSTRAINT ukjb553gu8ityk06dbghpfbmroy UNIQUE (code);


--
-- Name: ems_price_policy ukks5jbvi22h30gn1g1fysder64; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_price_policy
    ADD CONSTRAINT ukks5jbvi22h30gn1g1fysder64 UNIQUE (code);


--
-- Name: sys_module uknoavfxvjvs053hbvxfixe0gw2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_module
    ADD CONSTRAINT uknoavfxvjvs053hbvxfixe0gw2 UNIQUE (code);


--
-- Name: sys_role ukplpigyqwsqfn7mn66npgf9ftp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_role
    ADD CONSTRAINT ukplpigyqwsqfn7mn66npgf9ftp UNIQUE (code);


--
-- Name: sys_user ukpulp17fvich5aby4m0kc820h6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT ukpulp17fvich5aby4m0kc820h6 UNIQUE (phone);


--
-- Name: ems_energy_type ukqyk5p9pr4r421rh8un10ddyi6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_type
    ADD CONSTRAINT ukqyk5p9pr4r421rh8un10ddyi6 UNIQUE (code);


--
-- Name: sys_post ukr5b7w4kya2gmxcc1asyns6odk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_post
    ADD CONSTRAINT ukr5b7w4kya2gmxcc1asyns6odk UNIQUE (code);


--
-- Name: idx_alarm_config_limit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alarm_config_limit ON public.ems_alarm_config USING btree (limit_type_id);


--
-- Name: idx_alarm_config_meter_point; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alarm_config_meter_point ON public.ems_alarm_config USING btree (meter_point_id);


--
-- Name: idx_alarm_limit_type_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alarm_limit_type_code ON public.ems_alarm_limit_type USING btree (limit_code);


--
-- Name: idx_alarm_record_config; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alarm_record_config ON public.ems_alarm_record USING btree (config_id);


--
-- Name: idx_alarm_record_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alarm_record_time ON public.ems_alarm_record USING btree (trigger_time);


--
-- Name: idx_benchmark_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_benchmark_code ON public.ems_benchmark USING btree (code);


--
-- Name: idx_benchmark_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_benchmark_type ON public.ems_benchmark USING btree (type);


--
-- Name: idx_cpb_energy_unit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cpb_energy_unit ON public.ems_cost_policy_binding USING btree (energy_unit_id);


--
-- Name: idx_cpb_price_policy; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cpb_price_policy ON public.ems_cost_policy_binding USING btree (price_policy_id);


--
-- Name: idx_data_source_gateway; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_data_source_gateway ON public.ems_data_source USING btree (gateway_id);


--
-- Name: idx_data_source_protocol; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_data_source_protocol ON public.ems_data_source USING btree (protocol);


--
-- Name: idx_dict_data_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dict_data_type ON public.sys_dict_data USING btree (type_code);


--
-- Name: idx_ecr_energy_unit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ecr_energy_unit ON public.ems_energy_cost_record USING btree (energy_unit_id);


--
-- Name: idx_ecr_period_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ecr_period_type ON public.ems_energy_cost_record USING btree (period_type);


--
-- Name: idx_ecr_record_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ecr_record_date ON public.ems_energy_cost_record USING btree (record_date);


--
-- Name: idx_energy_data_composite; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_data_composite ON public.ems_energy_data USING btree (meter_point_id, data_time, time_type);


--
-- Name: idx_energy_data_point; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_data_point ON public.ems_energy_data USING btree (meter_point_id);


--
-- Name: idx_energy_data_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_data_time ON public.ems_energy_data USING btree (data_time, time_type);


--
-- Name: idx_energy_data_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_data_type ON public.ems_energy_data USING btree (energy_type_id);


--
-- Name: idx_energy_type_category; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_type_category ON public.ems_energy_type USING btree (category);


--
-- Name: idx_energy_type_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_type_code ON public.ems_energy_type USING btree (code);


--
-- Name: idx_energy_unit_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_unit_code ON public.ems_energy_unit USING btree (code);


--
-- Name: idx_energy_unit_parent; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_unit_parent ON public.ems_energy_unit USING btree (parent_id);


--
-- Name: idx_energy_unit_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_energy_unit_type ON public.ems_energy_unit USING btree (unit_type);


--
-- Name: idx_equipment_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_equipment_code ON public.ems_equipment USING btree (code);


--
-- Name: idx_equipment_energy_unit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_equipment_energy_unit ON public.ems_equipment USING btree (energy_unit_id);


--
-- Name: idx_gateway_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_gateway_code ON public.ems_gateway USING btree (code);


--
-- Name: idx_gateway_energy_unit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_gateway_energy_unit ON public.ems_gateway USING btree (energy_unit_id);


--
-- Name: idx_knowledge_energy_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_knowledge_energy_type ON public.ems_knowledge_article USING btree (energy_type_id);


--
-- Name: idx_knowledge_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_knowledge_status ON public.ems_knowledge_article USING btree (status);


--
-- Name: idx_meter_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meter_code ON public.ems_meter USING btree (code);


--
-- Name: idx_meter_energy_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meter_energy_type ON public.ems_meter USING btree (energy_type_id);


--
-- Name: idx_meter_point_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meter_point_code ON public.ems_meter_point USING btree (code);


--
-- Name: idx_meter_point_energy_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meter_point_energy_type ON public.ems_meter_point USING btree (energy_type_id);


--
-- Name: idx_meter_point_meter; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meter_point_meter ON public.ems_meter_point USING btree (meter_id);


--
-- Name: idx_meter_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_meter_type ON public.ems_meter USING btree (type);


--
-- Name: idx_permission_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_permission_code ON public.sys_permission USING btree (code);


--
-- Name: idx_permission_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_permission_id ON public.sys_permission USING btree (id);


--
-- Name: idx_policy_issuing_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_policy_issuing_date ON public.ems_policy USING btree (issuing_date);


--
-- Name: idx_policy_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_policy_type ON public.ems_policy USING btree (type);


--
-- Name: idx_price_policy_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_price_policy_code ON public.ems_price_policy USING btree (code);


--
-- Name: idx_price_policy_energy_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_price_policy_energy_type ON public.ems_price_policy USING btree (energy_type_id);


--
-- Name: idx_price_policy_item_policy; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_price_policy_item_policy ON public.ems_price_policy_item USING btree (policy_id);


--
-- Name: idx_product_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_code ON public.ems_product USING btree (code);


--
-- Name: idx_product_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_status ON public.ems_product USING btree (status);


--
-- Name: idx_production_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_production_date ON public.ems_production_record USING btree (record_date);


--
-- Name: idx_production_energy_unit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_production_energy_unit ON public.ems_production_record USING btree (energy_unit_id);


--
-- Name: idx_production_product; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_production_product ON public.ems_production_record USING btree (product_name);


--
-- Name: idx_pvd_data_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pvd_data_time ON public.ems_peak_valley_data USING btree (data_time, time_type);


--
-- Name: idx_pvd_energy_unit; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pvd_energy_unit ON public.ems_peak_valley_data USING btree (energy_unit_id);


--
-- Name: idx_pvd_meter_point; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pvd_meter_point ON public.ems_peak_valley_data USING btree (meter_point_id);


--
-- Name: idx_role_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_role_code ON public.sys_role USING btree (code);


--
-- Name: idx_role_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_role_id ON public.sys_role USING btree (id);


--
-- Name: idx_role_perm_permission_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_role_perm_permission_id ON public.sys_role_permission USING btree (permission_id);


--
-- Name: idx_role_perm_role_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_role_perm_role_id ON public.sys_role_permission USING btree (role_id);


--
-- Name: idx_saving_project_liable; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_saving_project_liable ON public.ems_energy_saving_project USING btree (liable_person);


--
-- Name: idx_saving_project_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_saving_project_status ON public.ems_energy_saving_project USING btree (status);


--
-- Name: idx_sys_dept_parent; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_dept_parent ON public.sys_dept USING btree (parent_id);


--
-- Name: idx_sys_dept_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_dept_status ON public.sys_dept USING btree (status);


--
-- Name: idx_sys_log_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_log_time ON public.sys_log USING btree (created_at);


--
-- Name: idx_sys_log_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_log_type ON public.sys_log USING btree (log_type);


--
-- Name: idx_sys_log_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_log_user ON public.sys_log USING btree (username);


--
-- Name: idx_sys_login_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_login_status ON public.sys_login_log USING btree (status);


--
-- Name: idx_sys_login_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_login_time ON public.sys_login_log USING btree (login_time);


--
-- Name: idx_sys_menu_parent; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_menu_parent ON public.sys_menu USING btree (parent_id);


--
-- Name: idx_sys_oper_log_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_oper_log_status ON public.sys_operation_log USING btree (status);


--
-- Name: idx_sys_oper_log_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_oper_log_time ON public.sys_operation_log USING btree (created_at);


--
-- Name: idx_sys_oper_log_title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_oper_log_title ON public.sys_operation_log USING btree (title);


--
-- Name: idx_sys_post_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_post_code ON public.sys_post USING btree (code);


--
-- Name: idx_sys_user_phone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_user_phone ON public.sys_user USING btree (phone);


--
-- Name: idx_sys_user_username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sys_user_username ON public.sys_user USING btree (username);


--
-- Name: idx_user_notice_notice_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_notice_notice_id ON public.sys_user_notice USING btree (notice_id);


--
-- Name: idx_user_notice_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_notice_user_id ON public.sys_user_notice USING btree (user_id);


--
-- Name: idx_user_permission_permission_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_permission_permission_id ON public.sys_user_permission USING btree (permission_id);


--
-- Name: idx_user_permission_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_permission_user_id ON public.sys_user_permission USING btree (user_id);


--
-- Name: idx_user_post_post_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_post_post_id ON public.sys_user_post USING btree (post_id);


--
-- Name: idx_user_post_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_post_user_id ON public.sys_user_post USING btree (user_id);


--
-- Name: idx_user_role_role_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_role_role_id ON public.sys_user_role USING btree (role_id);


--
-- Name: idx_user_role_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_role_user_id ON public.sys_user_role USING btree (user_id);


--
-- Name: ems_equipment fk10egc3sjv1hqpxosvkbfqgrr7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_equipment
    ADD CONSTRAINT fk10egc3sjv1hqpxosvkbfqgrr7 FOREIGN KEY (energy_unit_id) REFERENCES public.ems_energy_unit(id);


--
-- Name: ems_time_period_price fk2a7o9rx5066t0bxuhqovre0jv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_time_period_price
    ADD CONSTRAINT fk2a7o9rx5066t0bxuhqovre0jv FOREIGN KEY (price_policy_id) REFERENCES public.ems_price_policy(id);


--
-- Name: sys_menu fk2jrf4gb0gjqi8882gxytpxnhe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_menu
    ADD CONSTRAINT fk2jrf4gb0gjqi8882gxytpxnhe FOREIGN KEY (parent_id) REFERENCES public.sys_menu(id);


--
-- Name: ems_meter fk2u7l39m9oc8l1x0gbrm030auy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter
    ADD CONSTRAINT fk2u7l39m9oc8l1x0gbrm030auy FOREIGN KEY (data_source_id) REFERENCES public.ems_data_source(id);


--
-- Name: ems_peak_valley_data fk2xxsklymdmvnetmrqbh4v4qfv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_peak_valley_data
    ADD CONSTRAINT fk2xxsklymdmvnetmrqbh4v4qfv FOREIGN KEY (meter_point_id) REFERENCES public.ems_meter_point(id);


--
-- Name: ems_data_source fk4ooqkat90bq8bdplv00h2ntjd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_data_source
    ADD CONSTRAINT fk4ooqkat90bq8bdplv00h2ntjd FOREIGN KEY (gateway_id) REFERENCES public.ems_gateway(id);


--
-- Name: ems_peak_valley_data fk5rnu6abd4lmuhx0qomoybvqs7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_peak_valley_data
    ADD CONSTRAINT fk5rnu6abd4lmuhx0qomoybvqs7 FOREIGN KEY (energy_unit_id) REFERENCES public.ems_energy_unit(id);


--
-- Name: ems_gateway fk7vhm0u72mjn0bhdx33x1gp54a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_gateway
    ADD CONSTRAINT fk7vhm0u72mjn0bhdx33x1gp54a FOREIGN KEY (energy_unit_id) REFERENCES public.ems_energy_unit(id);


--
-- Name: ems_cost_policy_binding fk8o2swh51gx7j0nfgnq5t4ut1p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_cost_policy_binding
    ADD CONSTRAINT fk8o2swh51gx7j0nfgnq5t4ut1p FOREIGN KEY (energy_unit_id) REFERENCES public.ems_energy_unit(id);


--
-- Name: sys_dept fk8wb8qylwmt7squef8hedew4qe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_dept
    ADD CONSTRAINT fk8wb8qylwmt7squef8hedew4qe FOREIGN KEY (manager_id) REFERENCES public.sys_user(id);


--
-- Name: sys_role_permission fk9q28ewrhntqeipl1t04kh1be7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_role_permission
    ADD CONSTRAINT fk9q28ewrhntqeipl1t04kh1be7 FOREIGN KEY (role_id) REFERENCES public.sys_role(id);


--
-- Name: ems_meter_point fk9raqe49pu25u5l2657351qs6u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter_point
    ADD CONSTRAINT fk9raqe49pu25u5l2657351qs6u FOREIGN KEY (energy_type_id) REFERENCES public.ems_energy_type(id);


--
-- Name: ems_alarm_config fk_alarm_config_meter_point; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_alarm_config
    ADD CONSTRAINT fk_alarm_config_meter_point FOREIGN KEY (meter_point_id) REFERENCES public.ems_meter_point(id);


--
-- Name: ems_price_policy_item fkaujit7a1vuuxapn5k3ki5u3dk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_price_policy_item
    ADD CONSTRAINT fkaujit7a1vuuxapn5k3ki5u3dk FOREIGN KEY (policy_id) REFERENCES public.ems_price_policy(id);


--
-- Name: sys_user fkb3pkx0wbo6o8i8lj0gxr37v1n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT fkb3pkx0wbo6o8i8lj0gxr37v1n FOREIGN KEY (dept_id) REFERENCES public.sys_dept(id);


--
-- Name: sys_user_role fkb40xxfch70f5qnyfw8yme1n1s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_role
    ADD CONSTRAINT fkb40xxfch70f5qnyfw8yme1n1s FOREIGN KEY (user_id) REFERENCES public.sys_user(id);


--
-- Name: sys_permission fkbvx60lch0yucxxb6pm8i4s3r5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_permission
    ADD CONSTRAINT fkbvx60lch0yucxxb6pm8i4s3r5 FOREIGN KEY (module_id) REFERENCES public.sys_module(id);


--
-- Name: ems_energy_cost_record fkcr8m7fqdmugsugc5aec8ofv9a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_cost_record
    ADD CONSTRAINT fkcr8m7fqdmugsugc5aec8ofv9a FOREIGN KEY (energy_type_id) REFERENCES public.ems_energy_type(id);


--
-- Name: sys_dept fkd5ou5hch26i1tk6m8jc4fpirw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_dept
    ADD CONSTRAINT fkd5ou5hch26i1tk6m8jc4fpirw FOREIGN KEY (parent_id) REFERENCES public.sys_dept(id);


--
-- Name: ems_alarm_record fkde5gs6tyxlc7em2ikb2tjgxh5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_alarm_record
    ADD CONSTRAINT fkde5gs6tyxlc7em2ikb2tjgxh5 FOREIGN KEY (config_id) REFERENCES public.ems_alarm_config(id);


--
-- Name: ems_price_policy fkdm20pwebfqrjy1x2p78lk7s19; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_price_policy
    ADD CONSTRAINT fkdm20pwebfqrjy1x2p78lk7s19 FOREIGN KEY (energy_type_id) REFERENCES public.ems_energy_type(id);


--
-- Name: sys_user_permission fke1o35okbrlv0wbsq4o8tw6mbp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_permission
    ADD CONSTRAINT fke1o35okbrlv0wbsq4o8tw6mbp FOREIGN KEY (permission_id) REFERENCES public.sys_permission(id);


--
-- Name: ems_energy_cost_record fke4enn5gcecv26cv6qqw5v67j4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_cost_record
    ADD CONSTRAINT fke4enn5gcecv26cv6qqw5v67j4 FOREIGN KEY (energy_unit_id) REFERENCES public.ems_energy_unit(id);


--
-- Name: ems_meter_point fkeoh88jlbidlicytes7sy48uim; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter_point
    ADD CONSTRAINT fkeoh88jlbidlicytes7sy48uim FOREIGN KEY (meter_id) REFERENCES public.ems_meter(id);


--
-- Name: sys_user_role fkhh52n8vd4ny9ff4x9fb8v65qx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_role
    ADD CONSTRAINT fkhh52n8vd4ny9ff4x9fb8v65qx FOREIGN KEY (role_id) REFERENCES public.sys_role(id);


--
-- Name: ems_energy_data fkhxwy6yrxwkmng9culxcvybt25; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_data
    ADD CONSTRAINT fkhxwy6yrxwkmng9culxcvybt25 FOREIGN KEY (energy_type_id) REFERENCES public.ems_energy_type(id);


--
-- Name: ems_meter fkimy8spwpso0kru9e6k2kr5t74; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter
    ADD CONSTRAINT fkimy8spwpso0kru9e6k2kr5t74 FOREIGN KEY (energy_type_id) REFERENCES public.ems_energy_type(id);


--
-- Name: ems_cost_policy_binding fkj65jboyv49b49jsk2v9ibcfn6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_cost_policy_binding
    ADD CONSTRAINT fkj65jboyv49b49jsk2v9ibcfn6 FOREIGN KEY (price_policy_id) REFERENCES public.ems_price_policy(id);


--
-- Name: ems_meter fkkoulbk3qfxd9qcljn9ivf80ae; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter
    ADD CONSTRAINT fkkoulbk3qfxd9qcljn9ivf80ae FOREIGN KEY (energy_unit_id) REFERENCES public.ems_energy_unit(id);


--
-- Name: ems_energy_data fkl2rph682la6pe73bnxopxccwn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_data
    ADD CONSTRAINT fkl2rph682la6pe73bnxopxccwn FOREIGN KEY (meter_point_id) REFERENCES public.ems_meter_point(id);


--
-- Name: sys_role_dept fkmdoybh4v5t2ooi48m3307n7fx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_role_dept
    ADD CONSTRAINT fkmdoybh4v5t2ooi48m3307n7fx FOREIGN KEY (role_id) REFERENCES public.sys_role(id);


--
-- Name: sys_user_post fkng2mc7xcmyerevvobtw95bmu9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_post
    ADD CONSTRAINT fkng2mc7xcmyerevvobtw95bmu9 FOREIGN KEY (post_id) REFERENCES public.sys_post(id);


--
-- Name: ems_alarm_config fknguophx1udpdc43j06f6m3wdg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_alarm_config
    ADD CONSTRAINT fknguophx1udpdc43j06f6m3wdg FOREIGN KEY (limit_type_id) REFERENCES public.ems_alarm_limit_type(id);


--
-- Name: ems_energy_unit fknlkr4e061x5t6wx2u6broi9sd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_unit
    ADD CONSTRAINT fknlkr4e061x5t6wx2u6broi9sd FOREIGN KEY (parent_id) REFERENCES public.ems_energy_unit(id);


--
-- Name: ems_meter fko56nq0xbio15g04g3lh34q55j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter
    ADD CONSTRAINT fko56nq0xbio15g04g3lh34q55j FOREIGN KEY (gateway_id) REFERENCES public.ems_gateway(id);


--
-- Name: sys_role_permission fkomxrs8a388bknvhjokh440waq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_role_permission
    ADD CONSTRAINT fkomxrs8a388bknvhjokh440waq FOREIGN KEY (permission_id) REFERENCES public.sys_permission(id);


--
-- Name: sys_user_permission fkoo9oirp69aql5xrde05q948ja; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_permission
    ADD CONSTRAINT fkoo9oirp69aql5xrde05q948ja FOREIGN KEY (user_id) REFERENCES public.sys_user(id);


--
-- Name: sys_user_post fkpjx0gi8xwm66cp1w1jvi4hc57; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sys_user_post
    ADD CONSTRAINT fkpjx0gi8xwm66cp1w1jvi4hc57 FOREIGN KEY (user_id) REFERENCES public.sys_user(id);


--
-- Name: ems_energy_unit_point fkpuo4y0owrgxop99sru6qqbtdf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_unit_point
    ADD CONSTRAINT fkpuo4y0owrgxop99sru6qqbtdf FOREIGN KEY (energy_unit_id) REFERENCES public.ems_energy_unit(id);


--
-- Name: ems_meter fkr9nq2wwgs21wma5bd7wos93gr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_meter
    ADD CONSTRAINT fkr9nq2wwgs21wma5bd7wos93gr FOREIGN KEY (equipment_id) REFERENCES public.ems_equipment(id);


--
-- Name: ems_energy_unit_point fksuy4wdg82ye58frkig3ubp606; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_energy_unit_point
    ADD CONSTRAINT fksuy4wdg82ye58frkig3ubp606 FOREIGN KEY (meter_point_id) REFERENCES public.ems_meter_point(id);


--
-- Name: ems_benchmark fkuimhqqp60r0iotcwwu346jel; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ems_benchmark
    ADD CONSTRAINT fkuimhqqp60r0iotcwwu346jel FOREIGN KEY (energy_type_id) REFERENCES public.ems_energy_type(id);


--
-- PostgreSQL database dump complete
--


--
-- Data for Name: sys_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.sys_user (id, username, password, real_name, status, super_admin, created_at, updated_at) 
VALUES (1, 'admin', '$2a$mYkIwrDLxj04AjOZzv2Nv.TWbT/roKNJ4pHOadd.sUiS3cwq6eNjC', '系统管理员', 0, true, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

--
-- Name: sys_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sys_user_id_seq', 1, true);
