spring:
  application:
    name: terra-ems
  main:
    lazy-initialization: true
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/terra_ems?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  

  
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: ${SPRING_DATA_REDIS_DATABASE:0}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 3000
  
  session:
    store-type: ${SPRING_SESSION_STORE_TYPE:redis}
    redis:
      namespace: terra:ems:session
      configure-action: none

server:
  port: ${PORT:8081}
  address: 0.0.0.0
  servlet:
    context-path: /api

logging:
  level:
    com.terra.ems: debug
    org.springframework.security: debug
  file:
    name: ${LOGGING_FILE_NAME:/app/logs/terra-ems.log}

terra:
  api:
    secret: ${TERRA_INTERNAL_SECRET:terra-default-secret-2026}
  cache:
    allow-null-values: true
    separator: ":"
